CREATE SEQUENCE public.pky_sequence
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1;

CREATE TABLE dnb (
    apiid bigint NOT NULL,
    datetime date,
    technician integer,
    evtype character varying(20),
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    ischore boolean,
    reason text,
    warn text,
    eart integer,
    farm character varying(100),
    evnote character varying(100),
    tech character varying(100),
    barnnm character varying(100),
    brd character varying(100),
    ownernm character varying(100),
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(100),
    evid integer,
    evloc character varying(100),
    evnum smallint,
    evnumt smallint,
    evsirebreed character(2),
    evsirenaab character(10),
    evsirestudcd integer,
    msdevbarn character(10),
    other1 character varying,
    other2 character varying,
    other2id integer,
    other5id character varying,
    pky bigint
);

CREATE TABLE public.inventory (
    apiid integer NOT NULL,
    stable_id integer NOT NULL,
    inherd boolean,
    animal integer,
    bdate date,
    bdateweek date,
    brd character varying(100),
    chbrdnote1 character varying(100),
    dhfr smallint,
    bfcf smallint,
    eart integer,
    locat character varying(100),
    other1 character varying,
    other1note character varying(100),
    ownernm character varying(100),
    sex character(1),
    sicrbr character varying(100),
    sirebreed character(2),
    date date,
    sirc character varying(20),
    purcdate date,
    purcsrcmr character varying(50),
    cint character varying(100),
    bv_me305 character varying(20),
    chbrdnote character varying(100),
    seruresult character varying,
    sirsbr character(2),
    pky bigint DEFAULT nextval('public.pky_sequence'::regclass),
    ageseruresult integer,
    solddate character varying,
    solddied character varying
);

CREATE TABLE abortions (
    apiid integer NOT NULL,
    datetime date,
    technician integer,
    evtype character varying(20),
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    cause character varying(100),
    is_fresh double precision,
    abortion_date date,
    eart integer,
    farm character varying(100),
    abrt_cause character varying(100),
    barnnm character varying(100),
    brd character varying(100),
    ownernm character varying(100),
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(20),
    evid bigint,
    evloc character varying(100),
    evnote character varying(100),
    evnum smallint,
    evnumt smallint,
    evsirebreed character(2),
    evsirenaab character(10),
    evsirestudcd integer,
    msdevbarn character varying(50),
    other1 character varying,
    other2 character varying,
    other2id integer,
    other5id character varying,
    pky bigint
);

CREATE TABLE births (
    apiid integer NOT NULL,
    datetime integer,
    weight numeric(6,2),
    evgroup smallint,
    eart integer,
    farm character varying(150),
    barnnm character varying(50),
    bdate date,
    brd character varying(50),
    locat character varying(100),
    other1 character varying,
    other2 integer,
    other5id character varying(50),
    ownernm character varying(100),
    sex character(1),
    pky bigint,
    sir character varying(150),
    mother integer,
    date date
);

CREATE TABLE breedings (
    apiid integer NOT NULL,
    datetime integer,
    evtype character varying(20),
    technician integer,
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    isabort integer,
    isunique integer,
    ischore boolean,
    age1blt smallint,
    agemo smallint,
    barnnm character varying(100),
    bdate date,
    brd character varying(100),
    eart integer,
    locat character varying(100),
    ownernm character varying(100),
    sex character(1),
    assoprot character varying(100),
    bredabort boolean,
    bredopen boolean,
    bredpreg boolean,
    bredreas character varying(100),
    bredsexed integer,
    bredunk boolean,
    conceptrate smallint,
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(20),
    evid bigint,
    evloc character varying(100),
    evnote character varying(100),
    evnum smallint,
    evnumt smallint,
    evsirebreed character(2),
    evsirenaab character(10),
    evsirestudcd integer,
    evweek date,
    invldbrd boolean,
    msdevbarn character varying(50),
    other1 character varying,
    other2 integer,
    other2id integer,
    other5id character varying,
    proto character varying(100),
    spevtyp character varying(50),
    tech character varying(100),
    levdesc character varying(50),
    pky bigint,
    rtseq character varying(50)
);

CREATE TABLE culls (
    apiid integer NOT NULL,
    technician integer,
    evtype character varying(20),
    date date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    ischore boolean,
    age1blt smallint,
    agemo smallint,
    barnnm character varying(100),
    bdate date,
    brd character varying(100),
    eart integer,
    locat character varying(100),
    other1 character varying,
    other2 integer,
    other5id character varying(50),
    ownernm character varying(100),
    sex character(1),
    age smallint,
    cullprimar character varying(100),
    culltype character varying(100),
    dim smallint,
    evageday smallint,
    evagemo smallint,
    evid integer,
    evloc character varying(100),
    evnote character varying(100),
    evnum numeric,
    evnumt smallint,
    evsirenaab character varying,
    evweek date,
    other2id integer,
    spevtyp character varying(20),
    tech character varying(100),
    evfdat date,
    animal integer,
    datetime integer,
    levdesc character varying(50),
    pky bigint,
    solddate date,
    solddied integer
);

CREATE TABLE diagnosis (
    apiid integer NOT NULL,
    datetime integer,
    technician integer,
    evtype character varying(20),
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    age1blt smallint,
    agemo smallint,
    barnnm character varying(100),
    bdate date,
    brd character varying(100),
    eart integer,
    locat character varying(100),
    other1 character varying,
    other2 character varying,
    other5id character varying,
    ownernm character varying(100),
    sex character(1),
    age smallint,
    assoprot character varying(100),
    dim smallint,
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(100),
    evid integer,
    evloc character varying(100),
    evnote character varying(200),
    evnum smallint,
    evnumt smallint,
    evsirebreed character(2),
    evsirenaab character(10),
    evweek date,
    evsirestudcd integer,
    msdevbarn character(10),
    other2id integer,
    spevtyp character varying(50),
    tech character varying(50),
    evdate date,
    animal integer,
    levdesc character varying(50),
    pky bigint
);

CREATE TABLE dryoffs (
    apiid bigint NOT NULL,
    datetime date,
    technician integer,
    evtype character varying(20),
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    ischore boolean,
    treatment character varying(50),
    sealant character varying(50),
    evlink character varying(255),
    eart integer,
    farm character varying(100),
    evnote character varying(100),
    tech character varying(100),
    barnnm character varying(100),
    brd character varying(100),
    ownernm character varying(100),
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(100),
    evid integer,
    evloc character varying(100),
    evnum smallint,
    evnumt smallint,
    evsirebreed character(2),
    evsirenaab character(10),
    evsirestudcd integer,
    msdevbarn character(10),
    other1 character varying,
    other2 character varying,
    other2id integer,
    other5id character varying,
    pky bigint
);

CREATE TABLE freshs (
    apiid bigint NOT NULL,
    technician integer,
    evtype character varying(20),
    date date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    ischore boolean,
    age1blt smallint,
    agemo smallint,
    barnnm character varying(100),
    bdate date,
    brd character varying(100),
    eart integer,
    locat character varying(100),
    other1 character varying,
    other2 integer,
    other5id character varying,
    ownernm character varying(100),
    sex character(1),
    age smallint,
    dead double precision,
    dead24 double precision,
    deadfemale double precision,
    deadmale double precision,
    dim smallint,
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(100),
    evid integer,
    evloc character varying(100),
    evnote text,
    evsirebreed character(2),
    evsirenaab character(10),
    evweek date,
    evsirestudcd integer,
    female smallint,
    freshev character varying,
    frshassist smallint,
    frshcount smallint,
    frshease smallint,
    msdevbarn character(10),
    other2id integer,
    spevtyp character varying(10),
    tech character varying(50),
    male smallint,
    nocalves smallint,
    stillborn smallint,
    datetime integer,
    levdesc character varying(50),
    pky bigint
);

CREATE TABLE hoofs (
    apiid integer NOT NULL,
    technician integer,
    evtype character varying(20),
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    ischore boolean,
    age1blt smallint,
    agemo smallint,
    barnnm character varying(100),
    bdate date,
    brd character varying(100),
    eart integer,
    locat character varying(100),
    other1 character varying,
    other2 character varying,
    other5id character varying,
    ownernm character varying(100),
    sex character(1),
    age smallint,
    dim smallint,
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(100),
    evid integer,
    evloc character varying(100),
    evnote character varying(100),
    evnum smallint,
    evnumt smallint,
    evweek date,
    msdevbarn character varying(50),
    other2id integer,
    spevtyp character varying(50),
    tech character varying(50),
    evdate date,
    animal integer,
    datetime integer,
    limb character varying(50),
    levdesc character varying(50),
    treatment character varying(50),
    side character varying(50),
    pky bigint
);

CREATE TABLE moves (
    id integer NOT NULL,
    datetime integer,
    technician integer,
    evtype character varying(20),
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    ischore boolean,
    pen bigint,
    reason text,
    eart integer,
    farm character varying(100),
    evnote character varying(100),
    tech character varying(100),
    barnnm character varying(50),
    brd character varying(50),
    ownernm character varying(100),
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(100),
    evid bigint,
    evloc character varying(100),
    evnum smallint,
    evnumt smallint,
    evsirebreed character(2),
    evsirenaab character(10),
    evsirestudcd integer,
    msdevbarn character(10),
    other1 integer,
    other2 integer,
    other2id integer,
    other5id integer,
    pky bigint
);

CREATE TABLE pregchecks (
    apiid bigint NOT NULL,
    datetime integer,
    technician integer,
    evtype character varying(20),
    date date,
    evfdat date,
    evage smallint,
    evdim smallint,
    evlact smallint,
    evlagr smallint,
    evpen smallint,
    preg_type character varying(100),
    ischore boolean,
    evresult character varying(10),
    sex character(5),
    evcount integer,
    dcc integer,
    evstructure character varying(50),
    side character varying(20),
    evmethod character varying(100),
    reason_data json,
    eart integer,
    farm character varying(100),
    evnote character varying(100),
    tech character varying(100),
    barnnm character varying(50),
    brd character varying(50),
    ownernm character varying(100),
    evageday smallint,
    evagemo smallint,
    evgap smallint,
    evgaprange character varying(100),
    evid integer,
    evloc character varying(100),
    evnum smallint,
    evnumt smallint,
    evsirebreed character(2),
    evsirenaab character(10),
    evsirestudcd integer,
    msdevbarn character varying(50),
    other1 integer,
    other2 integer,
    other2id integer,
    other5id integer,
    pky bigint
);

ALTER TABLE public.inventory
    ALTER COLUMN pky SET DEFAULT nextval('public.pky_sequence');
ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (apiid);
ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pky_key UNIQUE (pky);
ALTER TABLE ONLY public.abortions
    ADD CONSTRAINT fk_abortions_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky) NOT VALID;
ALTER TABLE ONLY public.births
    ADD CONSTRAINT fk_births_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky) NOT VALID;
ALTER TABLE ONLY public.breedings
    ADD CONSTRAINT fk_breedings_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky) NOT VALID;
ALTER TABLE ONLY public.culls
    ADD CONSTRAINT fk_culls_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky) NOT VALID;
ALTER TABLE ONLY public.diagnosis
    ADD CONSTRAINT fk_diagnosis_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky) NOT VALID;
ALTER TABLE ONLY public.dryoffs
    ADD CONSTRAINT fk_dryoffs_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky);
ALTER TABLE ONLY public.freshs
    ADD CONSTRAINT fk_freshs_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky) NOT VALID;
ALTER TABLE ONLY public.hoofs
    ADD CONSTRAINT fk_hoofs_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky) NOT VALID;
ALTER TABLE ONLY public.moves
    ADD CONSTRAINT fk_moves_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky);
ALTER TABLE ONLY public.pregchecks
    ADD CONSTRAINT fk_pregchecks_inventory FOREIGN KEY (pky) REFERENCES public.inventory(pky);
ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk_inventory_stable FOREIGN KEY (stable_id) REFERENCES public.stables(id);
